# Start ./server

version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
      args:
        - SKIP_BUILD=${SKIP_BUILD:-false}
    ports:
      - "3000:3000"
      - "3306:3306"
      - "19530:19530"
      - "19121:19121"
    volumes:
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: pnpm run start:prod

  app:
    build:
      context: .
      dockerfile: ./packages/app/Dockerfile
      args:
        - SKIP_BUILD=${SKIP_BUILD:-false}
    ports:
      - "3001:3001"
    volumes:
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REACT_APP_API_URL=http://server:3000
    command: sh -c "pnpm run start"
    depends_on:
      - server
