# Start ./server
# You have to pre-build those dist/ files before using this docker-compose file

version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
      args:
        - SKIP_BUILD=true
        - SKIP_INSTALL=true
    ports:
      - "3000:3000"
    volumes:
      - ./packages/server:/app/packages/server
      - ./packages/server/.env:/app/packages/server/.env
      - ./node_modules:/app/node_modules
      - ./packages/server/dist:/app/packages/server/dist
      - ./packages/server/node_modules:/app/packages/server/node_modules
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: pnpm run start:prod

  app:
    build:
      context: .
      dockerfile: ./packages/app/Dockerfile
      args:
        - SKIP_BUILD=true
        - SKIP_INSTALL=true
    ports:
      - "3001:3001"
    volumes:
      - ./packages/app:/app/packages/app
      - ./node_modules:/app/node_modules
      - ./packages/app/dist:/app/packages/app/dist
      - ./packages/app/node_modules:/app/packages/app/node_modules
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REACT_APP_API_URL=http://server:3000
    command: sh -c "pnpm run start"
    depends_on:
      - server
