# Start ./server
# You have to pre-build those dist/ files before using this docker-compose file

version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/server:/app
      - /app/node_modules
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: pnpm start

  app:
    build:
      context: .
      dockerfile: ./packages/app/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./packages/app:/app
      - /app/node_modules
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REACT_APP_API_URL=http://server:3000
    command: sh -c "pnpm run build && pnpm start"
    depends_on:
      - server
